### ISSUE TITLE
Common key is always invalid

### ISSUE THREAD

**Issue by xxmichibxx** [Pokes303/NUSPackerPlus#1]
I've created a file name "WiiU_Common_Key.txt" (with was not mentioned by the README) and pasted the Wii U retail common key, but the program still says invalid common key. I also don't want to rule out a mistake on my part.

Image: https://imgur.com/a/HblCtOz

Best regards,
Michael

**Comment by xxmichibxx** [comment]
I mentioned that I was using the dev common key but I won't work with the retail key either

**Comment by Shapy06** [comment]
ok with D7B00402659BA2ABD2CB0DB27FA2B656

**Comment by xxmichibxx** [comment]
> ok with D7B00402659BA2ABD2CB0DB27FA2B656

Thanks for your reply. Apparently it only works if the letters are all capitalized (case-sensitive). Also the "WiiU_Common_Key.txt" is only vaild, if it contains "Common Key File generated by NUSPackerPlus" in the second line.
